swagger: '2.0'
info:
  title: Agile HTTP API
  description: The Agile HTTP API to interact with local DBus objects
  version: 1.0.0
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
# the domain of the service
host: localhost:8080
# array of all schemes that your API supports
schemes:
  - http
# will be prefixed to all paths
basePath: /api
consumes:
  - application/json
produces:
  - application/json
# security:
#   - type: basic
#     in: header
#   - type: oauth2
#     authorizationUrl: /api/oauth
#     flow: [implicit, password, application, accessCode]

externalDocs:
  url: http://agile-iot.github.io/agile-api-spec
  description: DBus AGILE API spec

tags:
  - name: DeviceManager
    description: Device management API
  - name: Device
    description: Device related API
  - name: ProtocolManager
    description: Protocol management API
  - name: Protocol
    description: Protocol related API

paths:
  '/device/{deviceId}/execute/{command}':
    parameters:
      -
        name: deviceId
        in: path
        description: 'Agile device Id'
        required: true
        type: string
      -
        name: command
        in: path
        description: 'Operation name to be performed'
        required: true
        type: string
    post:
      tags:
        - Device
      description: 'Perform an action on the device'
      parameters:
        -
          name: payload
          in: body
          description: "The content to be sent to the device to perform an actuation\n"
          schema:
            type: string
      responses:
        '200':
          description: 'Action sent'
        '204':
          description: 'Action sent, no response received'
  '/device/{deviceId}/{componentId}/subscribe':
    parameters:
      -
        name: deviceId
        in: path
        description: 'Agile device Id'
        required: true
        type: string
      -
        name: componentId
        in: path
        description: 'Agile component name, like a sensor'
        required: true
        type: string
    post:
      tags:
        - Device
      description: "Enable a subscription to a data stream. Asynchronous data updates will\nbe delivered via websocket.\n"
      responses:
        '200':
          description: 'Subscription registered'
    delete:
      tags:
        - Device
      description: 'Unsubscribe from a data stream'
      responses:
        '200':
          description: Unsubscribed
  '/device/{deviceId}/{componentId}':
    parameters:
      -
        name: deviceId
        in: path
        description: 'Agile device Id'
        required: true
        type: string
      -
        name: componentId
        in: path
        description: 'Agile component name, like a sensor'
        required: true
        type: string
    get:
      tags:
        - Device
      description: 'Read from a device component'
      responses:
        '200':
          description: 'Read done'
        '204':
          description: 'No data available'
    post:
      tags:
        - Device
      description: 'Write to a device component'
      responses:
        '200':
          description: 'Write sent'
        '204':
          description: 'Write sent, no results returned'
  '/device/{deviceId}/{componentId}/lastUpdate':
    parameters:
      -
        name: deviceId
        in: path
        description: 'Agile device Id'
        required: true
        type: string
      -
        name: componentId
        in: path
        description: 'Agile component name, like a sensor'
        required: true
        type: string
    get:
      tags:
        - Device
      description: 'Get the last record fetched from the device'
      responses:
        '200':
          description: 'Record fetched'
        '204':
          description: 'No data available'
        '404':
          description: 'Device not available'
  /devices:
    get:
      tags:
        - DeviceManager
      description: 'List all registered devices'
      responses:
        '200':
          description: 'List the registered device'
          schema:
            type: array
            $ref: '#/definitions/DeviceDefinition'
          examples:
            application/json:
              -
                id: aaa1-bbb2-ccc3-ddd4
                name: SensorTag
                path: iot.agile.device.SensorTag
                streams:
                  -
                    name: temperature
                    unit: celsius
                  -
                    name: light
                    unit: lumen
                  -
                    name: accelerometer
        '204':
          description: 'Device list is empty'
    post:
      tags:
        - DeviceManager
      parameters:
        -
          name: body
          in: body
          description: 'The request body describing a device'
          required: true
          schema:
            $ref: '#/definitions/DeviceDefinition'
      description: 'Creates a new device definition'
      responses:
        '200':
          description: 'Device created'
  '/devices/{deviceId}':
    parameters:
      -
        name: deviceId
        in: path
        description: 'Agile device Id'
        required: true
        type: string
    get:
      tags:
        - DeviceManager
      description: 'Get a device definition'
      responses:
        '200':
          description: 'Device loaded'
          schema:
            $ref: '#/definitions/DeviceDefinition'
          examples:
            application/json:
              id: aaa1-bbb2-ccc3-ddd4
              name: SensorTag
              path: iot.agile.device.SensorTag
              streams:
                -
                  name: temperature
                -
                  name: accelerometer
        '404':
          description: 'Device not found'
    put:
      tags:
        - DeviceManager
      parameters:
        -
          name: body
          in: body
          description: 'The request body describing a device'
          required: true
          schema:
            $ref: '#/definitions/DeviceDefinition'
      description: 'Update a device definition'
      responses:
        '200':
          description: 'Device updated'
        '404':
          description: 'Device not found'
    delete:
      tags:
        - DeviceManager
      parameters:
        -
          name: body
          in: body
          description: 'The request body describing a device'
          required: true
          schema:
            $ref: '#/definitions/DeviceDefinition'
      description: 'Delete a device definition and unregister it'
      responses:
        '200':
          description: 'Device removed'
        '404':
          description: 'Device not found'
  '/protocol/{protocolId}/connection/{deviceId}':
    parameters:
      -
        name: protocolId
        in: path
        description: 'Agile Id of the protocol'
        required: true
        type: string
      -
        name: deviceId
        in: path
        description: 'Agile internal Id of the protocol'
        required: true
        type: string
    post:
      tags:
        - Protocol
      description: 'Connect to the device'
      responses:
        '200':
          description: 'Connection initialized'
        '404':
          description: 'Device not found'
    delete:
      tags:
        - Protocol
      description: 'Disconnect from the device'
      responses:
        '200':
          description: 'Disconnection completed'
        '404':
          description: 'Device not found'
  '/protocol/{protocolId}/discovery':
    parameters:
      -
        name: protocolId
        in: path
        description: 'Agile Id of the protocol'
        required: true
        type: string
    post:
      tags:
        - Protocol
      description: 'Start the discovery process'
      responses:
        '200':
          description: 'Discovery started'
        '404':
          description: 'Device not found'
    delete:
      tags:
        - Protocol
      description: 'Stop the discovery process'
      responses:
        '200':
          description: 'Discovery process stopped'
        '404':
          description: 'Device not found'
  '/protocol/{protocolId}/{deviceId}':
    parameters:
      -
        name: protocolId
        in: path
        description: 'Agile internal Id of the protocol'
        required: true
        type: string
      -
        name: deviceId
        in: path
        description: 'Agile protocol Id of the device'
        required: true
        type: string
    post:
      tags:
        - Protocol
      description: 'Call a write via protocol'
      parameters:
        -
          name: data
          in: body
          description: 'An object containing the content to write'
          required: true
          schema:
            $ref: '#/definitions/ProtocolMessage'
      responses:
        '200':
          description: 'Write suceeded'
        '404':
          description: 'Device or component not found'
    get:
      tags:
        - Protocol
      description: 'Call a read via protocol'
      responses:
        '200':
          description: 'Read suceeded'
          schema:
            $ref: '#/definitions/RecordObject'
        '404':
          description: 'Device or component not found'
  /protocols:
    get:
      tags:
        - ProtocolManager
      description: 'Get the list of registered protocols'
      responses:
        '200':
          description: 'Protocols list provided'
          schema:
            $ref: '#/definitions/ProtocolOverview'
          examples:
            application/json:
              -
                id: BLE
                name: 'Bluetooth LE'
                interface: iot.agile.protocol.BLE
                status: AVAILABLE
              -
                id: ZigBee
                name: 'ZigBee communication protocol'
                interface: iot.agile.protocol.ZigBee
                status: AVAILABLE
        '204':
          description: 'No protocols registered.'
  '/protocols/{protocolId}':
    parameters:
      -
        name: protocolId
        in: path
        description: 'Agile protocol Id'
        required: true
        type: string
    post:
      tags:
        - ProtocolManager
      description: 'Register a new Dbus object implementing the protocol API'
      responses:
        '202':
          description: 'Protocol has been added'
        '400':
          description: 'An error occured processing the request'
    delete:
      tags:
        - ProtocolManager
      description: 'Unregister a Dbus Protocol object reference'
      responses:
        '200':
          description: 'Protocol unregistered'
        '404':
          description: 'Protocol not found'
  /protocols/devices:
    get:
      tags:
        - ProtocolManager
      description: 'List all discovered devices on all available protocols'
      responses:
        '200':
          description: "The list of devices found via discovery\n"
          schema:
            type: array
            $ref: '#/definitions/DeviceOverview'
          examples:
            application/json:
              -
                name: SensorTag
                id: 'AA:BB:CC:DD'
                protocol: iot.agile.protocol.BLE
                status: AVAILABLE
              -
                name: LightDimmer
                id: 'CC:DD:AA:BB'
                protocol: iot.agile.protocol.Zwave
                status: AVAILABLE
  /protocols/discovery:
    get:
      tags:
        - ProtocolManager
      description: 'Return the status of discovery on the available protocols'
      responses:
        '200':
          description: "Return the list of protocol discovery status\n"
          schema:
            $ref: '#/definitions/DiscoveryStatus'
          examples:
            application/json:
              -
                name: BLE
                status: RUNNING
              -
                name: ZigBee
                status: NONE
              -
                name: ZWave
                status: FAILURE
    post:
      tags:
        - ProtocolManager
      description: 'Start a device discovery on all available protocols'
      responses:
        '204':
          description: "The discovery has been successfully started on all the regitered\nprotocols; asynchronous updates will be sent via websocket\n"
        '409':
          description: "Indicates that discovery has been requested to the underlying\nprotocols but one or more reported a failure\n"
    delete:
      tags:
        - ProtocolManager
      description: 'Stop a device discovery if previously initiated'
      responses:
        '204':
          description: "The discovery has been successfully stopped on all the regitered\nprotocols; There will be no further device updates via websocket\n"
        '409':
          description: "Indicates that discovery has been requested to stop on the underlying\nprotocols but one or more reported a failure\n"
  
definitions:
  DeviceOverview:
    description: 'An overview of a device a protocol knows about'
    type: object
    properties:
      name:
        description: 'Friendly name of the device'
        type: string
      protocol:
        description: 'Protocol reference for this device'
        type: string
      id:
        description: 'Protocol level id used to identify and access the device'
        type: string
      status:
        enum:
          - CONNECTED
          - DISCONNECTED
          - AVAILABLE
          - UNAVAILABLE
  DiscoveryStatus:
    type: object
    properties:
      name:
        description: 'Name of the protocol'
        type: string
      status:
        enum:
          - NONE
          - RUNNING
          - FAILURE
  ProtocolMessage:
    type: object
    properties:
      data:
        type: string
      format:
        type: string
  ProtocolOverview:
    type: object
    properties:
      name:
        description: 'The protocol name'
        type: string
      id:
        description: 'the internal code identifying the protocol'
        type: string
      interface:
        description: 'The DBus interface reference'
        type: string
      status:
        $ref: '#/definitions/ProtocolStatus'
  ProtocolStatus:
    description: "Identify a status of the Protocol, indicating if operational (AVAILABLE) or\nif for some reason further user-side checks are required.\n"
    enum:
      - AVAILABLE
      - UNAVAILABLE
      - NOT_CONFIGURED
      - DISABLED
      - ENABLED
      - FAILURE
  ChannelTypeEnum:
    enum:
      - Number
      - String
      - Boolean
      - GeoPoint
      - Object
  DeviceComponent:
    description: 'A device component from which get a data stream, like a sensor'
    type: object
    properties:
      id:
        type: string
      unit:
        type: string
      properties:
        $ref: '#/definitions/KeyValue'
  DeviceDefinition:
    description: 'A device definition that contains informations describing the current device'
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      description:
        type: string
      path:
        description: 'DBus specific path to reach the object instance'
        type: string
      properties:
        $ref: '#/definitions/KeyValue'
      streams:
        description: 'A list of components from which get data streams'
        type: array
        items:
          $ref: '#/definitions/DeviceComponent'
  RecordObject:
    type: object
    properties:
      DeviceId:
        description: 'The Agile Id for the device'
        type: string
      ComponentId:
        description: 'The component Id for the device, like the sensor name'
        type: string
      Value:
        description: 'The value stored'
        type: string
      Format:
        description: 'A format description to read the data value'
        type: string
      LastUpdate:
        description: 'A UNIX timestamp rapresenting the last update of a record'
        type: number
  KeyValue:
    description: 'A list of key/value pairs'
    type: object
  
